/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

module autograbbercfg;
private import dfl.all;
import commondata;
import autograbber;

class IntWrapper
{
	int i;
	this(int n){i=n;}
}

class AutoGrabberCfg: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.listview.ListView lvItems;
	dfl.button.Button btnAll;
	dfl.button.Button btnNone;
	dfl.button.Button btnOk;
	dfl.button.Button btnCancel;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeAutoGrabberCfg();
		
		// Other AutoGrabberCfg initialization code here.
		auto col = new ColumnHeader("Item name");
		col.width = lvItems.width-6-15;
		lvItems.columns.add(col);
		
		this.handleCreated ~= &formCreated;
	}
	
	void formCreated(Object o, EventArgs ea)
	{
		foreach(int type, ref obj;objectData)
			//if(obj.flags & ObjectDataFlags.Item)
			if(!(obj.flags & ObjectDataFlags.Object) && obj.family != ObjectFamily.Character && obj.family != ObjectFamily.Sign && obj.nameStr.length>1 && type>=4)
			{
				auto item = new dfl.listview.ListViewItem(obj.nameStr);
				item.tag = new IntWrapper(type);
				lvItems.items.add(item);
				item.checked = grabThis[type];
			}
	}
	
	private void initializeAutoGrabberCfg()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.3 code begins here.
		//~DFL Form
		formBorderStyle = dfl.all.FormBorderStyle.FIXED_TOOLWINDOW;
		maximizeBox = false;
		minimizeBox = false;
		showInTaskbar = false;
		text = "Item types";
		clientSize = dfl.all.Size(178, 415);
		//~DFL dfl.listview.ListView=lvItems
		lvItems = new dfl.listview.ListView();
		lvItems.name = "lvItems";
		lvItems.autoArrange = false;
		lvItems.checkBoxes = true;
		lvItems.fullRowSelect = true;
		lvItems.hideSelection = false;
		lvItems.labelWrap = false;
		lvItems.multiSelect = false;
		lvItems.view = dfl.all.View.DETAILS;
		lvItems.bounds = dfl.all.Rect(8, 32, 160, 352);
		lvItems.parent = this;
		//~DFL dfl.button.Button=btnAll
		btnAll = new dfl.button.Button();
		btnAll.name = "btnAll";
		btnAll.text = "All";
		btnAll.bounds = dfl.all.Rect(8, 8, 75, 19);
		btnAll.parent = this;
		//~DFL dfl.button.Button=btnNone
		btnNone = new dfl.button.Button();
		btnNone.name = "btnNone";
		btnNone.text = "None";
		btnNone.bounds = dfl.all.Rect(93, 8, 75, 19);
		btnNone.parent = this;
		//~DFL dfl.button.Button=btnOk
		btnOk = new dfl.button.Button();
		btnOk.name = "btnOk";
		btnOk.text = "OK";
		btnOk.bounds = dfl.all.Rect(8, 390, 75, 19);
		btnOk.parent = this;
		//~DFL dfl.button.Button=btnCancel
		btnCancel = new dfl.button.Button();
		btnCancel.name = "btnCancel";
		btnCancel.text = "Cancel";
		btnCancel.bounds = dfl.all.Rect(93, 390, 75, 19);
		btnCancel.parent = this;
		//~Entice Designer 0.8.3 code ends here.
		btnAll.click ~= &btnAllClick;
		btnNone.click ~= &btnNoneClick;
		btnOk.click ~= &btnOkClick;
		btnCancel.click ~= &btnCancelClick;
	}
	
	void btnAllClick(Object o, EventArgs ea)
	{
		foreach(item;lvItems.items)
			item.checked = true;
	}
	
	void btnNoneClick(Object o, EventArgs ea)
	{
		foreach(item;lvItems.items)
			item.checked = false;
	}
	
	void btnOkClick(Object o, EventArgs ea)
	{
		foreach(item;lvItems.items)
			grabThis[(cast(IntWrapper)item.tag).i] = item.checked;
		saveGrabList();
		close();
	}
	
	void btnCancelClick(Object o, EventArgs ea)
	{
		close();
	}
}
